# Form implementation generated from reading ui file 'templates.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Templates_Form(object):
    def setupUi(self, templates):
        templates.setObjectName("templates")
        templates.resize(600, 432)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("гор.PNG"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        templates.setWindowIcon(icon)
        templates.setStyleSheet("background-image: url(:/newPrefix/1669935661_41-kartinkin-net-p-fon-dlya-saita-svetlii-vkontakte-43.jpg);\n"
"border: 1px solid #4682B4;")
        self.label = QtWidgets.QLabel(parent=templates)
        self.label.setGeometry(QtCore.QRect(69, 10, 451, 50))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(6, 6, 6);\n"
"    background-color: rgba(255, 255, 255, 150);\n"
"    border-radius: 10px;\n"
"    padding: 3px;")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(parent=templates)
        self.frame.setGeometry(QtCore.QRect(40, 80, 241, 271))
        self.frame.setStyleSheet("\n"
"        QFrame {\n"
"            background: #ffffff;\n"
"            border-radius: 8px;\n"
"            border: 1px solid #adb5bd;\n"
"            padding: 10px;\n"
"        }\n"
"    ")
        self.frame.setObjectName("frame")
        self.lineEdit_name_temp = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_name_temp.setGeometry(QtCore.QRect(10, 30, 201, 25))
        self.lineEdit_name_temp.setStyleSheet("\n"
"        QLineEdit {\n"
"            background: white;\n"
"            border: 1px solid #87ceeb;\n"
"            border-radius: 5px;\n"
"            padding: 3px;\n"
"        }\n"
"     ")
        self.lineEdit_name_temp.setObjectName("lineEdit_name_temp")
        self.lineEdit_width_temp_2 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_width_temp_2.setGeometry(QtCore.QRect(10, 70, 201, 25))
        self.lineEdit_width_temp_2.setStyleSheet("\n"
"        QLineEdit {\n"
"            background: white;\n"
"            border: 1px solid #87ceeb;\n"
"            border-radius: 5px;\n"
"            padding: 3px;\n"
"        }\n"
"     ")
        self.lineEdit_width_temp_2.setObjectName("lineEdit_width_temp_2")
        self.lineEdit_heigth_temp_3 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_heigth_temp_3.setGeometry(QtCore.QRect(10, 110, 201, 25))
        self.lineEdit_heigth_temp_3.setStyleSheet("\n"
"        QLineEdit {\n"
"            background: white;\n"
"            border: 1px solid #87ceeb;\n"
"            border-radius: 5px;\n"
"            padding: 3px;\n"
"        }\n"
"     ")
        self.lineEdit_heigth_temp_3.setObjectName("lineEdit_heigth_temp_3")
        self.lineEdit_depth_temp_4 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_depth_temp_4.setGeometry(QtCore.QRect(10, 150, 201, 25))
        self.lineEdit_depth_temp_4.setStyleSheet("\n"
"        QLineEdit {\n"
"            background: white;\n"
"            border: 1px solid #87ceeb;\n"
"            border-radius: 5px;\n"
"            padding: 3px;\n"
"        }\n"
"     ")
        self.lineEdit_depth_temp_4.setObjectName("lineEdit_depth_temp_4")
        self.lineEdit_fire = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_fire.setGeometry(QtCore.QRect(10, 190, 201, 25))
        self.lineEdit_fire.setStyleSheet("\n"
"        QLineEdit {\n"
"            background: white;\n"
"            border: 1px solid #87ceeb;\n"
"            border-radius: 5px;\n"
"            padding: 3px;\n"
"        }\n"
"     ")
        self.lineEdit_fire.setObjectName("lineEdit_fire")
        self.foundation_height = QtWidgets.QLineEdit(parent=self.frame)
        self.foundation_height.setGeometry(QtCore.QRect(10, 230, 201, 25))
        self.foundation_height.setStyleSheet("\n"
"        QLineEdit {\n"
"            background: white;\n"
"            border: 1px solid #87ceeb;\n"
"            border-radius: 5px;\n"
"            padding: 3px;\n"
"        }\n"
"     ")
        self.foundation_height.setObjectName("foundation_height")
        self.frame_2 = QtWidgets.QFrame(parent=templates)
        self.frame_2.setGeometry(QtCore.QRect(310, 80, 261, 271))
        self.frame_2.setStyleSheet("\n"
"         QFrame {\n"
"            background: #ffffff;\n"
"            border-radius: 8px;\n"
"            border: 1px solid #adb5bd;\n"
"            padding: 10px;\n"
"        }\n"
"    ")
        self.frame_2.setObjectName("frame_2")
        self.comboBox_material = QtWidgets.QComboBox(parent=self.frame_2)
        self.comboBox_material.setGeometry(QtCore.QRect(10, 30, 231, 25))
        self.comboBox_material.setStyleSheet("\n"
"        QComboBox {\n"
"            background: white;\n"
"            border: 1px solid #87ceeb;\n"
"            border-radius: 5px;\n"
"            padding: 3px;\n"
"        }\n"
"     ")
        self.comboBox_material.setCurrentText("")
        self.comboBox_material.setObjectName("comboBox_material")
        self.lineEdit_windy = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_windy.setGeometry(QtCore.QRect(10, 180, 231, 20))
        self.lineEdit_windy.setObjectName("lineEdit_windy")
        self.lineEdit_snow = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_snow.setGeometry(QtCore.QRect(10, 150, 231, 20))
        self.lineEdit_snow.setObjectName("lineEdit_snow")
        self.lineEdit_type_wall = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_type_wall.setGeometry(QtCore.QRect(10, 70, 231, 20))
        self.lineEdit_type_wall.setObjectName("lineEdit_type_wall")
        self.lineEdit_roof = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_roof.setGeometry(QtCore.QRect(10, 110, 231, 20))
        self.lineEdit_roof.setObjectName("lineEdit_roof")
        self.wall_thickness = QtWidgets.QLineEdit(parent=self.frame_2)
        self.wall_thickness.setGeometry(QtCore.QRect(10, 210, 231, 20))
        self.wall_thickness.setObjectName("wall_thickness")
        self.foundation_thickness = QtWidgets.QLineEdit(parent=self.frame_2)
        self.foundation_thickness.setGeometry(QtCore.QRect(10, 240, 231, 20))
        self.foundation_thickness.setObjectName("foundation_thickness")
        self.pushButton_save_new_temp = QtWidgets.QPushButton(parent=templates)
        self.pushButton_save_new_temp.setGeometry(QtCore.QRect(190, 360, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_save_new_temp.setFont(font)
        self.pushButton_save_new_temp.setStyleSheet("\n"
"QPushButton {\n"
"        background: #000086;\n"
"        color: rgb(255, 255, 255);\n"
"        border-radius: 6px;\n"
"        font-size: 11px;\n"
"        border: 1px solid #6ab0de;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #006666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004d4d;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Downloads/free-icon-save-2550221.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_save_new_temp.setIcon(icon1)
        self.pushButton_save_new_temp.setObjectName("pushButton_save_new_temp")

        self.retranslateUi(templates)
        QtCore.QMetaObject.connectSlotsByName(templates)

    def retranslateUi(self, templates):
        _translate = QtCore.QCoreApplication.translate
        templates.setWindowTitle(_translate("templates", "Инженерный конструктор"))
        self.label.setText(_translate("templates", "<html><head/><body><p align=\"center\">✎ ИНЖЕНЕРНЫЙ ШАБЛОН</p></body></html>"))
        self.lineEdit_name_temp.setPlaceholderText(_translate("templates", "введите название"))
        self.lineEdit_width_temp_2.setPlaceholderText(_translate("templates", "введите ширину(мм)"))
        self.lineEdit_heigth_temp_3.setPlaceholderText(_translate("templates", "введите высоту(мм)"))
        self.lineEdit_depth_temp_4.setPlaceholderText(_translate("templates", "введите глубину(мм)"))
        self.lineEdit_fire.setPlaceholderText(_translate("templates", "введите класс пожарной безопасности"))
        self.foundation_height.setPlaceholderText(_translate("templates", "введите высоту фундамента(мм)"))
        self.lineEdit_windy.setPlaceholderText(_translate("templates", "введите ветровую нагрузку(кг/м^2)"))
        self.lineEdit_snow.setPlaceholderText(_translate("templates", "введите снеговую нагрузку(кг/м^2)"))
        self.lineEdit_type_wall.setPlaceholderText(_translate("templates", "введите тип стены"))
        self.lineEdit_roof.setPlaceholderText(_translate("templates", "введите тип крыши"))
        self.wall_thickness.setPlaceholderText(_translate("templates", "введите толщину стен(мм)"))
        self.foundation_thickness.setPlaceholderText(_translate("templates", "введите толщину фундамента(мм)"))
        self.pushButton_save_new_temp.setText(_translate("templates", "СОХРАНИТЬ ЧЕРТЁЖ"))
